# Generated by Django 5.0 on 2024-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageFile',
            field=models.ImageField(blank=True, upload_to='img/%y'),
        ),
    ]
