# Generated by Django 5.0 on 2024-01-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageFile',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
