# Generated by Django 5.0 on 2024-01-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_post_imagefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imageFile',
            new_name='image',
        ),
    ]
